### ISSUE TITLE
Deleted code samples

### ISSUE THREAD

**Issue by daniloraisi** [Azure-Samples/functions-custom-handlers#18]
Why did code samples for C#, Java, and Node were deleted by Pull Request #12?

**Comment by anthonychu** [comment]
Customers should be using the supported Azure Functions language workers for those languages, not custom handlers. We found that having them here led to confusions.

**Comment by daniloraisi** [comment]
I understand, but there are edge cases on Node, for example, that custom handlers saves a lot of time and work.

**Comment by anthonychu** [comment]
Can you share what these edge cases are? Would like to address them in the Node worker if possible.

**Comment by SIkebe** [comment]
>Customers should be using the supported Azure Functions language workers for those languages, not custom handlers.

@anthonychu  Then C# with .NET 5.0 supported?

**Comment by SIkebe** [comment]
Also README.md still includes those samples. Those links cause 404.
>The following samples demonstrate how to implement a custom handler in the following languages:
>
>- [C#](https://github.com/Azure-Samples/functions-custom-handlers/tree/master/CSharp)
>- [Go](https://github.com/Azure-Samples/functions-custom-handlers/tree/master/go)
>- [Java](https://github.com/Azure-Samples/functions-custom-handlers/tree/master/Java)
>- [JavaScript](https://github.com/Azure-Samples/functions-custom-handlers/tree/master/node)
>- [R](https://github.com/Azure-Samples/functions-custom-handlers/tree/master/R)
>- [Rust](https://github.com/Azure-Samples/functions-custom-handlers/tree/master/Rust)

**Comment by damoodamoo** [comment]
Could someone from the team elaborate on why they were removed? For Java, for instance, using a custom handler means:
- I can choose the version I want
- I can have DI
- I can use model binding / all the other Spring stuff
- I can use well established test frameworks

...why wouldn't I want that?

**Comment by ZaourbekGerikhanov** [comment]
@anthonychu for Node, there is one edge case that I can share.
If I have a big legacy project in Express.js with lots of endpoints and I want to deploy it to Azure Functions without rearchitecting my code, then Custom Handler can do the job.
